<?php
/**
 * ImportSepaPaymentMethodRequestDto
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Frisbii
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API
 *
 * REST API to manage Frisbii resources
 *
 * The version of the OpenAPI document: 1
 * Contact: support@frisbii.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Frisbii\Model;

use \ArrayAccess;
use \Frisbii\ObjectSerializer;

/**
 * ImportSepaPaymentMethodRequestDto Class Doc Comment
 *
 * @category Class
 * @package  Frisbii
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ImportSepaPaymentMethodRequestDto implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ImportSepaPaymentMethodRequestDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'creditorCountry' => 'string',
        'debtorIban' => 'string',
        'debtorName' => 'string',
        'reference' => 'string',
        'customer' => '\Frisbii\Model\CreateCustomer',
        'customerHandle' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'creditorCountry' => null,
        'debtorIban' => null,
        'debtorName' => null,
        'reference' => null,
        'customer' => null,
        'customerHandle' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'creditorCountry' => false,
        'debtorIban' => false,
        'debtorName' => false,
        'reference' => false,
        'customer' => false,
        'customerHandle' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'creditorCountry' => 'creditor_country',
        'debtorIban' => 'debtor_iban',
        'debtorName' => 'debtor_name',
        'reference' => 'reference',
        'customer' => 'customer',
        'customerHandle' => 'customer_handle'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'creditorCountry' => 'setCreditorCountry',
        'debtorIban' => 'setDebtorIban',
        'debtorName' => 'setDebtorName',
        'reference' => 'setReference',
        'customer' => 'setCustomer',
        'customerHandle' => 'setCustomerHandle'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'creditorCountry' => 'getCreditorCountry',
        'debtorIban' => 'getDebtorIban',
        'debtorName' => 'getDebtorName',
        'reference' => 'getReference',
        'customer' => 'getCustomer',
        'customerHandle' => 'getCustomerHandle'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const CREDITOR_COUNTRY_UNDEFINED = 'UNDEFINED';
    public const CREDITOR_COUNTRY_AC = 'AC';
    public const CREDITOR_COUNTRY_AD = 'AD';
    public const CREDITOR_COUNTRY_AE = 'AE';
    public const CREDITOR_COUNTRY_AF = 'AF';
    public const CREDITOR_COUNTRY_AG = 'AG';
    public const CREDITOR_COUNTRY_AI = 'AI';
    public const CREDITOR_COUNTRY_AL = 'AL';
    public const CREDITOR_COUNTRY_AM = 'AM';
    public const CREDITOR_COUNTRY_AN = 'AN';
    public const CREDITOR_COUNTRY_AO = 'AO';
    public const CREDITOR_COUNTRY_AQ = 'AQ';
    public const CREDITOR_COUNTRY_AR = 'AR';
    public const CREDITOR_COUNTRY__AS = 'AS';
    public const CREDITOR_COUNTRY_AT = 'AT';
    public const CREDITOR_COUNTRY_AU = 'AU';
    public const CREDITOR_COUNTRY_AW = 'AW';
    public const CREDITOR_COUNTRY_AX = 'AX';
    public const CREDITOR_COUNTRY_AZ = 'AZ';
    public const CREDITOR_COUNTRY_BA = 'BA';
    public const CREDITOR_COUNTRY_BB = 'BB';
    public const CREDITOR_COUNTRY_BD = 'BD';
    public const CREDITOR_COUNTRY_BE = 'BE';
    public const CREDITOR_COUNTRY_BF = 'BF';
    public const CREDITOR_COUNTRY_BG = 'BG';
    public const CREDITOR_COUNTRY_BH = 'BH';
    public const CREDITOR_COUNTRY_BI = 'BI';
    public const CREDITOR_COUNTRY_BJ = 'BJ';
    public const CREDITOR_COUNTRY_BL = 'BL';
    public const CREDITOR_COUNTRY_BM = 'BM';
    public const CREDITOR_COUNTRY_BN = 'BN';
    public const CREDITOR_COUNTRY_BO = 'BO';
    public const CREDITOR_COUNTRY_BQ = 'BQ';
    public const CREDITOR_COUNTRY_BR = 'BR';
    public const CREDITOR_COUNTRY_BS = 'BS';
    public const CREDITOR_COUNTRY_BT = 'BT';
    public const CREDITOR_COUNTRY_BU = 'BU';
    public const CREDITOR_COUNTRY_BV = 'BV';
    public const CREDITOR_COUNTRY_BW = 'BW';
    public const CREDITOR_COUNTRY_BY = 'BY';
    public const CREDITOR_COUNTRY_BZ = 'BZ';
    public const CREDITOR_COUNTRY_CA = 'CA';
    public const CREDITOR_COUNTRY_CC = 'CC';
    public const CREDITOR_COUNTRY_CD = 'CD';
    public const CREDITOR_COUNTRY_CF = 'CF';
    public const CREDITOR_COUNTRY_CG = 'CG';
    public const CREDITOR_COUNTRY_CH = 'CH';
    public const CREDITOR_COUNTRY_CI = 'CI';
    public const CREDITOR_COUNTRY_CK = 'CK';
    public const CREDITOR_COUNTRY_CL = 'CL';
    public const CREDITOR_COUNTRY_CM = 'CM';
    public const CREDITOR_COUNTRY_CN = 'CN';
    public const CREDITOR_COUNTRY_CO = 'CO';
    public const CREDITOR_COUNTRY_CP = 'CP';
    public const CREDITOR_COUNTRY_CR = 'CR';
    public const CREDITOR_COUNTRY_CS = 'CS';
    public const CREDITOR_COUNTRY_CU = 'CU';
    public const CREDITOR_COUNTRY_CV = 'CV';
    public const CREDITOR_COUNTRY_CW = 'CW';
    public const CREDITOR_COUNTRY_CX = 'CX';
    public const CREDITOR_COUNTRY_CY = 'CY';
    public const CREDITOR_COUNTRY_CZ = 'CZ';
    public const CREDITOR_COUNTRY_DE = 'DE';
    public const CREDITOR_COUNTRY_DG = 'DG';
    public const CREDITOR_COUNTRY_DJ = 'DJ';
    public const CREDITOR_COUNTRY_DK = 'DK';
    public const CREDITOR_COUNTRY_DM = 'DM';
    public const CREDITOR_COUNTRY__DO = 'DO';
    public const CREDITOR_COUNTRY_DZ = 'DZ';
    public const CREDITOR_COUNTRY_EA = 'EA';
    public const CREDITOR_COUNTRY_EC = 'EC';
    public const CREDITOR_COUNTRY_EE = 'EE';
    public const CREDITOR_COUNTRY_EG = 'EG';
    public const CREDITOR_COUNTRY_EH = 'EH';
    public const CREDITOR_COUNTRY_ER = 'ER';
    public const CREDITOR_COUNTRY_ES = 'ES';
    public const CREDITOR_COUNTRY_ET = 'ET';
    public const CREDITOR_COUNTRY_EU = 'EU';
    public const CREDITOR_COUNTRY_FI = 'FI';
    public const CREDITOR_COUNTRY_FJ = 'FJ';
    public const CREDITOR_COUNTRY_FK = 'FK';
    public const CREDITOR_COUNTRY_FM = 'FM';
    public const CREDITOR_COUNTRY_FO = 'FO';
    public const CREDITOR_COUNTRY_FR = 'FR';
    public const CREDITOR_COUNTRY_FX = 'FX';
    public const CREDITOR_COUNTRY_GA = 'GA';
    public const CREDITOR_COUNTRY_GB = 'GB';
    public const CREDITOR_COUNTRY_GD = 'GD';
    public const CREDITOR_COUNTRY_GE = 'GE';
    public const CREDITOR_COUNTRY_GF = 'GF';
    public const CREDITOR_COUNTRY_GG = 'GG';
    public const CREDITOR_COUNTRY_GH = 'GH';
    public const CREDITOR_COUNTRY_GI = 'GI';
    public const CREDITOR_COUNTRY_GL = 'GL';
    public const CREDITOR_COUNTRY_GM = 'GM';
    public const CREDITOR_COUNTRY_GN = 'GN';
    public const CREDITOR_COUNTRY_GP = 'GP';
    public const CREDITOR_COUNTRY_GQ = 'GQ';
    public const CREDITOR_COUNTRY_GR = 'GR';
    public const CREDITOR_COUNTRY_GS = 'GS';
    public const CREDITOR_COUNTRY_GT = 'GT';
    public const CREDITOR_COUNTRY_GU = 'GU';
    public const CREDITOR_COUNTRY_GW = 'GW';
    public const CREDITOR_COUNTRY_GY = 'GY';
    public const CREDITOR_COUNTRY_HK = 'HK';
    public const CREDITOR_COUNTRY_HM = 'HM';
    public const CREDITOR_COUNTRY_HN = 'HN';
    public const CREDITOR_COUNTRY_HR = 'HR';
    public const CREDITOR_COUNTRY_HT = 'HT';
    public const CREDITOR_COUNTRY_HU = 'HU';
    public const CREDITOR_COUNTRY_IC = 'IC';
    public const CREDITOR_COUNTRY_ID = 'ID';
    public const CREDITOR_COUNTRY_IE = 'IE';
    public const CREDITOR_COUNTRY_IL = 'IL';
    public const CREDITOR_COUNTRY_IM = 'IM';
    public const CREDITOR_COUNTRY_IN = 'IN';
    public const CREDITOR_COUNTRY_IO = 'IO';
    public const CREDITOR_COUNTRY_IQ = 'IQ';
    public const CREDITOR_COUNTRY_IR = 'IR';
    public const CREDITOR_COUNTRY_IS = 'IS';
    public const CREDITOR_COUNTRY_IT = 'IT';
    public const CREDITOR_COUNTRY_JE = 'JE';
    public const CREDITOR_COUNTRY_JM = 'JM';
    public const CREDITOR_COUNTRY_JO = 'JO';
    public const CREDITOR_COUNTRY_JP = 'JP';
    public const CREDITOR_COUNTRY_KE = 'KE';
    public const CREDITOR_COUNTRY_KG = 'KG';
    public const CREDITOR_COUNTRY_KH = 'KH';
    public const CREDITOR_COUNTRY_KI = 'KI';
    public const CREDITOR_COUNTRY_KM = 'KM';
    public const CREDITOR_COUNTRY_KN = 'KN';
    public const CREDITOR_COUNTRY_KP = 'KP';
    public const CREDITOR_COUNTRY_KR = 'KR';
    public const CREDITOR_COUNTRY_KW = 'KW';
    public const CREDITOR_COUNTRY_KY = 'KY';
    public const CREDITOR_COUNTRY_KZ = 'KZ';
    public const CREDITOR_COUNTRY_LA = 'LA';
    public const CREDITOR_COUNTRY_LB = 'LB';
    public const CREDITOR_COUNTRY_LC = 'LC';
    public const CREDITOR_COUNTRY_LI = 'LI';
    public const CREDITOR_COUNTRY_LK = 'LK';
    public const CREDITOR_COUNTRY_LR = 'LR';
    public const CREDITOR_COUNTRY_LS = 'LS';
    public const CREDITOR_COUNTRY_LT = 'LT';
    public const CREDITOR_COUNTRY_LU = 'LU';
    public const CREDITOR_COUNTRY_LV = 'LV';
    public const CREDITOR_COUNTRY_LY = 'LY';
    public const CREDITOR_COUNTRY_MA = 'MA';
    public const CREDITOR_COUNTRY_MC = 'MC';
    public const CREDITOR_COUNTRY_MD = 'MD';
    public const CREDITOR_COUNTRY_ME = 'ME';
    public const CREDITOR_COUNTRY_MF = 'MF';
    public const CREDITOR_COUNTRY_MG = 'MG';
    public const CREDITOR_COUNTRY_MH = 'MH';
    public const CREDITOR_COUNTRY_MK = 'MK';
    public const CREDITOR_COUNTRY_ML = 'ML';
    public const CREDITOR_COUNTRY_MM = 'MM';
    public const CREDITOR_COUNTRY_MN = 'MN';
    public const CREDITOR_COUNTRY_MO = 'MO';
    public const CREDITOR_COUNTRY_MP = 'MP';
    public const CREDITOR_COUNTRY_MQ = 'MQ';
    public const CREDITOR_COUNTRY_MR = 'MR';
    public const CREDITOR_COUNTRY_MS = 'MS';
    public const CREDITOR_COUNTRY_MT = 'MT';
    public const CREDITOR_COUNTRY_MU = 'MU';
    public const CREDITOR_COUNTRY_MV = 'MV';
    public const CREDITOR_COUNTRY_MW = 'MW';
    public const CREDITOR_COUNTRY_MX = 'MX';
    public const CREDITOR_COUNTRY_MY = 'MY';
    public const CREDITOR_COUNTRY_MZ = 'MZ';
    public const CREDITOR_COUNTRY_NA = 'NA';
    public const CREDITOR_COUNTRY_NC = 'NC';
    public const CREDITOR_COUNTRY_NE = 'NE';
    public const CREDITOR_COUNTRY_NF = 'NF';
    public const CREDITOR_COUNTRY_NG = 'NG';
    public const CREDITOR_COUNTRY_NI = 'NI';
    public const CREDITOR_COUNTRY_NL = 'NL';
    public const CREDITOR_COUNTRY_NO = 'NO';
    public const CREDITOR_COUNTRY_NP = 'NP';
    public const CREDITOR_COUNTRY_NR = 'NR';
    public const CREDITOR_COUNTRY_NT = 'NT';
    public const CREDITOR_COUNTRY_NU = 'NU';
    public const CREDITOR_COUNTRY_NZ = 'NZ';
    public const CREDITOR_COUNTRY_OM = 'OM';
    public const CREDITOR_COUNTRY_PA = 'PA';
    public const CREDITOR_COUNTRY_PE = 'PE';
    public const CREDITOR_COUNTRY_PF = 'PF';
    public const CREDITOR_COUNTRY_PG = 'PG';
    public const CREDITOR_COUNTRY_PH = 'PH';
    public const CREDITOR_COUNTRY_PK = 'PK';
    public const CREDITOR_COUNTRY_PL = 'PL';
    public const CREDITOR_COUNTRY_PM = 'PM';
    public const CREDITOR_COUNTRY_PN = 'PN';
    public const CREDITOR_COUNTRY_PR = 'PR';
    public const CREDITOR_COUNTRY_PS = 'PS';
    public const CREDITOR_COUNTRY_PT = 'PT';
    public const CREDITOR_COUNTRY_PW = 'PW';
    public const CREDITOR_COUNTRY_PY = 'PY';
    public const CREDITOR_COUNTRY_QA = 'QA';
    public const CREDITOR_COUNTRY_RE = 'RE';
    public const CREDITOR_COUNTRY_RO = 'RO';
    public const CREDITOR_COUNTRY_RS = 'RS';
    public const CREDITOR_COUNTRY_RU = 'RU';
    public const CREDITOR_COUNTRY_RW = 'RW';
    public const CREDITOR_COUNTRY_SA = 'SA';
    public const CREDITOR_COUNTRY_SB = 'SB';
    public const CREDITOR_COUNTRY_SC = 'SC';
    public const CREDITOR_COUNTRY_SD = 'SD';
    public const CREDITOR_COUNTRY_SE = 'SE';
    public const CREDITOR_COUNTRY_SF = 'SF';
    public const CREDITOR_COUNTRY_SG = 'SG';
    public const CREDITOR_COUNTRY_SH = 'SH';
    public const CREDITOR_COUNTRY_SI = 'SI';
    public const CREDITOR_COUNTRY_SJ = 'SJ';
    public const CREDITOR_COUNTRY_SK = 'SK';
    public const CREDITOR_COUNTRY_SL = 'SL';
    public const CREDITOR_COUNTRY_SM = 'SM';
    public const CREDITOR_COUNTRY_SN = 'SN';
    public const CREDITOR_COUNTRY_SO = 'SO';
    public const CREDITOR_COUNTRY_SR = 'SR';
    public const CREDITOR_COUNTRY_SS = 'SS';
    public const CREDITOR_COUNTRY_ST = 'ST';
    public const CREDITOR_COUNTRY_SU = 'SU';
    public const CREDITOR_COUNTRY_SV = 'SV';
    public const CREDITOR_COUNTRY_SX = 'SX';
    public const CREDITOR_COUNTRY_SY = 'SY';
    public const CREDITOR_COUNTRY_SZ = 'SZ';
    public const CREDITOR_COUNTRY_TA = 'TA';
    public const CREDITOR_COUNTRY_TC = 'TC';
    public const CREDITOR_COUNTRY_TD = 'TD';
    public const CREDITOR_COUNTRY_TF = 'TF';
    public const CREDITOR_COUNTRY_TG = 'TG';
    public const CREDITOR_COUNTRY_TH = 'TH';
    public const CREDITOR_COUNTRY_TJ = 'TJ';
    public const CREDITOR_COUNTRY_TK = 'TK';
    public const CREDITOR_COUNTRY_TL = 'TL';
    public const CREDITOR_COUNTRY_TM = 'TM';
    public const CREDITOR_COUNTRY_TN = 'TN';
    public const CREDITOR_COUNTRY_TO = 'TO';
    public const CREDITOR_COUNTRY_TP = 'TP';
    public const CREDITOR_COUNTRY_TR = 'TR';
    public const CREDITOR_COUNTRY_TT = 'TT';
    public const CREDITOR_COUNTRY_TV = 'TV';
    public const CREDITOR_COUNTRY_TW = 'TW';
    public const CREDITOR_COUNTRY_TZ = 'TZ';
    public const CREDITOR_COUNTRY_UA = 'UA';
    public const CREDITOR_COUNTRY_UG = 'UG';
    public const CREDITOR_COUNTRY_UK = 'UK';
    public const CREDITOR_COUNTRY_UM = 'UM';
    public const CREDITOR_COUNTRY_US = 'US';
    public const CREDITOR_COUNTRY_UY = 'UY';
    public const CREDITOR_COUNTRY_UZ = 'UZ';
    public const CREDITOR_COUNTRY_VA = 'VA';
    public const CREDITOR_COUNTRY_VC = 'VC';
    public const CREDITOR_COUNTRY_VE = 'VE';
    public const CREDITOR_COUNTRY_VG = 'VG';
    public const CREDITOR_COUNTRY_VI = 'VI';
    public const CREDITOR_COUNTRY_VN = 'VN';
    public const CREDITOR_COUNTRY_VU = 'VU';
    public const CREDITOR_COUNTRY_WF = 'WF';
    public const CREDITOR_COUNTRY_WS = 'WS';
    public const CREDITOR_COUNTRY_XK = 'XK';
    public const CREDITOR_COUNTRY_YE = 'YE';
    public const CREDITOR_COUNTRY_YT = 'YT';
    public const CREDITOR_COUNTRY_YU = 'YU';
    public const CREDITOR_COUNTRY_ZA = 'ZA';
    public const CREDITOR_COUNTRY_ZM = 'ZM';
    public const CREDITOR_COUNTRY_ZR = 'ZR';
    public const CREDITOR_COUNTRY_ZW = 'ZW';
    public const CREDITOR_COUNTRY_UNKNOWN_DEFAULT_OPEN_API = 'unknown_default_open_api';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getCreditorCountryAllowableValues()
    {
        return [
            self::CREDITOR_COUNTRY_UNDEFINED,
            self::CREDITOR_COUNTRY_AC,
            self::CREDITOR_COUNTRY_AD,
            self::CREDITOR_COUNTRY_AE,
            self::CREDITOR_COUNTRY_AF,
            self::CREDITOR_COUNTRY_AG,
            self::CREDITOR_COUNTRY_AI,
            self::CREDITOR_COUNTRY_AL,
            self::CREDITOR_COUNTRY_AM,
            self::CREDITOR_COUNTRY_AN,
            self::CREDITOR_COUNTRY_AO,
            self::CREDITOR_COUNTRY_AQ,
            self::CREDITOR_COUNTRY_AR,
            self::CREDITOR_COUNTRY__AS,
            self::CREDITOR_COUNTRY_AT,
            self::CREDITOR_COUNTRY_AU,
            self::CREDITOR_COUNTRY_AW,
            self::CREDITOR_COUNTRY_AX,
            self::CREDITOR_COUNTRY_AZ,
            self::CREDITOR_COUNTRY_BA,
            self::CREDITOR_COUNTRY_BB,
            self::CREDITOR_COUNTRY_BD,
            self::CREDITOR_COUNTRY_BE,
            self::CREDITOR_COUNTRY_BF,
            self::CREDITOR_COUNTRY_BG,
            self::CREDITOR_COUNTRY_BH,
            self::CREDITOR_COUNTRY_BI,
            self::CREDITOR_COUNTRY_BJ,
            self::CREDITOR_COUNTRY_BL,
            self::CREDITOR_COUNTRY_BM,
            self::CREDITOR_COUNTRY_BN,
            self::CREDITOR_COUNTRY_BO,
            self::CREDITOR_COUNTRY_BQ,
            self::CREDITOR_COUNTRY_BR,
            self::CREDITOR_COUNTRY_BS,
            self::CREDITOR_COUNTRY_BT,
            self::CREDITOR_COUNTRY_BU,
            self::CREDITOR_COUNTRY_BV,
            self::CREDITOR_COUNTRY_BW,
            self::CREDITOR_COUNTRY_BY,
            self::CREDITOR_COUNTRY_BZ,
            self::CREDITOR_COUNTRY_CA,
            self::CREDITOR_COUNTRY_CC,
            self::CREDITOR_COUNTRY_CD,
            self::CREDITOR_COUNTRY_CF,
            self::CREDITOR_COUNTRY_CG,
            self::CREDITOR_COUNTRY_CH,
            self::CREDITOR_COUNTRY_CI,
            self::CREDITOR_COUNTRY_CK,
            self::CREDITOR_COUNTRY_CL,
            self::CREDITOR_COUNTRY_CM,
            self::CREDITOR_COUNTRY_CN,
            self::CREDITOR_COUNTRY_CO,
            self::CREDITOR_COUNTRY_CP,
            self::CREDITOR_COUNTRY_CR,
            self::CREDITOR_COUNTRY_CS,
            self::CREDITOR_COUNTRY_CU,
            self::CREDITOR_COUNTRY_CV,
            self::CREDITOR_COUNTRY_CW,
            self::CREDITOR_COUNTRY_CX,
            self::CREDITOR_COUNTRY_CY,
            self::CREDITOR_COUNTRY_CZ,
            self::CREDITOR_COUNTRY_DE,
            self::CREDITOR_COUNTRY_DG,
            self::CREDITOR_COUNTRY_DJ,
            self::CREDITOR_COUNTRY_DK,
            self::CREDITOR_COUNTRY_DM,
            self::CREDITOR_COUNTRY__DO,
            self::CREDITOR_COUNTRY_DZ,
            self::CREDITOR_COUNTRY_EA,
            self::CREDITOR_COUNTRY_EC,
            self::CREDITOR_COUNTRY_EE,
            self::CREDITOR_COUNTRY_EG,
            self::CREDITOR_COUNTRY_EH,
            self::CREDITOR_COUNTRY_ER,
            self::CREDITOR_COUNTRY_ES,
            self::CREDITOR_COUNTRY_ET,
            self::CREDITOR_COUNTRY_EU,
            self::CREDITOR_COUNTRY_FI,
            self::CREDITOR_COUNTRY_FJ,
            self::CREDITOR_COUNTRY_FK,
            self::CREDITOR_COUNTRY_FM,
            self::CREDITOR_COUNTRY_FO,
            self::CREDITOR_COUNTRY_FR,
            self::CREDITOR_COUNTRY_FX,
            self::CREDITOR_COUNTRY_GA,
            self::CREDITOR_COUNTRY_GB,
            self::CREDITOR_COUNTRY_GD,
            self::CREDITOR_COUNTRY_GE,
            self::CREDITOR_COUNTRY_GF,
            self::CREDITOR_COUNTRY_GG,
            self::CREDITOR_COUNTRY_GH,
            self::CREDITOR_COUNTRY_GI,
            self::CREDITOR_COUNTRY_GL,
            self::CREDITOR_COUNTRY_GM,
            self::CREDITOR_COUNTRY_GN,
            self::CREDITOR_COUNTRY_GP,
            self::CREDITOR_COUNTRY_GQ,
            self::CREDITOR_COUNTRY_GR,
            self::CREDITOR_COUNTRY_GS,
            self::CREDITOR_COUNTRY_GT,
            self::CREDITOR_COUNTRY_GU,
            self::CREDITOR_COUNTRY_GW,
            self::CREDITOR_COUNTRY_GY,
            self::CREDITOR_COUNTRY_HK,
            self::CREDITOR_COUNTRY_HM,
            self::CREDITOR_COUNTRY_HN,
            self::CREDITOR_COUNTRY_HR,
            self::CREDITOR_COUNTRY_HT,
            self::CREDITOR_COUNTRY_HU,
            self::CREDITOR_COUNTRY_IC,
            self::CREDITOR_COUNTRY_ID,
            self::CREDITOR_COUNTRY_IE,
            self::CREDITOR_COUNTRY_IL,
            self::CREDITOR_COUNTRY_IM,
            self::CREDITOR_COUNTRY_IN,
            self::CREDITOR_COUNTRY_IO,
            self::CREDITOR_COUNTRY_IQ,
            self::CREDITOR_COUNTRY_IR,
            self::CREDITOR_COUNTRY_IS,
            self::CREDITOR_COUNTRY_IT,
            self::CREDITOR_COUNTRY_JE,
            self::CREDITOR_COUNTRY_JM,
            self::CREDITOR_COUNTRY_JO,
            self::CREDITOR_COUNTRY_JP,
            self::CREDITOR_COUNTRY_KE,
            self::CREDITOR_COUNTRY_KG,
            self::CREDITOR_COUNTRY_KH,
            self::CREDITOR_COUNTRY_KI,
            self::CREDITOR_COUNTRY_KM,
            self::CREDITOR_COUNTRY_KN,
            self::CREDITOR_COUNTRY_KP,
            self::CREDITOR_COUNTRY_KR,
            self::CREDITOR_COUNTRY_KW,
            self::CREDITOR_COUNTRY_KY,
            self::CREDITOR_COUNTRY_KZ,
            self::CREDITOR_COUNTRY_LA,
            self::CREDITOR_COUNTRY_LB,
            self::CREDITOR_COUNTRY_LC,
            self::CREDITOR_COUNTRY_LI,
            self::CREDITOR_COUNTRY_LK,
            self::CREDITOR_COUNTRY_LR,
            self::CREDITOR_COUNTRY_LS,
            self::CREDITOR_COUNTRY_LT,
            self::CREDITOR_COUNTRY_LU,
            self::CREDITOR_COUNTRY_LV,
            self::CREDITOR_COUNTRY_LY,
            self::CREDITOR_COUNTRY_MA,
            self::CREDITOR_COUNTRY_MC,
            self::CREDITOR_COUNTRY_MD,
            self::CREDITOR_COUNTRY_ME,
            self::CREDITOR_COUNTRY_MF,
            self::CREDITOR_COUNTRY_MG,
            self::CREDITOR_COUNTRY_MH,
            self::CREDITOR_COUNTRY_MK,
            self::CREDITOR_COUNTRY_ML,
            self::CREDITOR_COUNTRY_MM,
            self::CREDITOR_COUNTRY_MN,
            self::CREDITOR_COUNTRY_MO,
            self::CREDITOR_COUNTRY_MP,
            self::CREDITOR_COUNTRY_MQ,
            self::CREDITOR_COUNTRY_MR,
            self::CREDITOR_COUNTRY_MS,
            self::CREDITOR_COUNTRY_MT,
            self::CREDITOR_COUNTRY_MU,
            self::CREDITOR_COUNTRY_MV,
            self::CREDITOR_COUNTRY_MW,
            self::CREDITOR_COUNTRY_MX,
            self::CREDITOR_COUNTRY_MY,
            self::CREDITOR_COUNTRY_MZ,
            self::CREDITOR_COUNTRY_NA,
            self::CREDITOR_COUNTRY_NC,
            self::CREDITOR_COUNTRY_NE,
            self::CREDITOR_COUNTRY_NF,
            self::CREDITOR_COUNTRY_NG,
            self::CREDITOR_COUNTRY_NI,
            self::CREDITOR_COUNTRY_NL,
            self::CREDITOR_COUNTRY_NO,
            self::CREDITOR_COUNTRY_NP,
            self::CREDITOR_COUNTRY_NR,
            self::CREDITOR_COUNTRY_NT,
            self::CREDITOR_COUNTRY_NU,
            self::CREDITOR_COUNTRY_NZ,
            self::CREDITOR_COUNTRY_OM,
            self::CREDITOR_COUNTRY_PA,
            self::CREDITOR_COUNTRY_PE,
            self::CREDITOR_COUNTRY_PF,
            self::CREDITOR_COUNTRY_PG,
            self::CREDITOR_COUNTRY_PH,
            self::CREDITOR_COUNTRY_PK,
            self::CREDITOR_COUNTRY_PL,
            self::CREDITOR_COUNTRY_PM,
            self::CREDITOR_COUNTRY_PN,
            self::CREDITOR_COUNTRY_PR,
            self::CREDITOR_COUNTRY_PS,
            self::CREDITOR_COUNTRY_PT,
            self::CREDITOR_COUNTRY_PW,
            self::CREDITOR_COUNTRY_PY,
            self::CREDITOR_COUNTRY_QA,
            self::CREDITOR_COUNTRY_RE,
            self::CREDITOR_COUNTRY_RO,
            self::CREDITOR_COUNTRY_RS,
            self::CREDITOR_COUNTRY_RU,
            self::CREDITOR_COUNTRY_RW,
            self::CREDITOR_COUNTRY_SA,
            self::CREDITOR_COUNTRY_SB,
            self::CREDITOR_COUNTRY_SC,
            self::CREDITOR_COUNTRY_SD,
            self::CREDITOR_COUNTRY_SE,
            self::CREDITOR_COUNTRY_SF,
            self::CREDITOR_COUNTRY_SG,
            self::CREDITOR_COUNTRY_SH,
            self::CREDITOR_COUNTRY_SI,
            self::CREDITOR_COUNTRY_SJ,
            self::CREDITOR_COUNTRY_SK,
            self::CREDITOR_COUNTRY_SL,
            self::CREDITOR_COUNTRY_SM,
            self::CREDITOR_COUNTRY_SN,
            self::CREDITOR_COUNTRY_SO,
            self::CREDITOR_COUNTRY_SR,
            self::CREDITOR_COUNTRY_SS,
            self::CREDITOR_COUNTRY_ST,
            self::CREDITOR_COUNTRY_SU,
            self::CREDITOR_COUNTRY_SV,
            self::CREDITOR_COUNTRY_SX,
            self::CREDITOR_COUNTRY_SY,
            self::CREDITOR_COUNTRY_SZ,
            self::CREDITOR_COUNTRY_TA,
            self::CREDITOR_COUNTRY_TC,
            self::CREDITOR_COUNTRY_TD,
            self::CREDITOR_COUNTRY_TF,
            self::CREDITOR_COUNTRY_TG,
            self::CREDITOR_COUNTRY_TH,
            self::CREDITOR_COUNTRY_TJ,
            self::CREDITOR_COUNTRY_TK,
            self::CREDITOR_COUNTRY_TL,
            self::CREDITOR_COUNTRY_TM,
            self::CREDITOR_COUNTRY_TN,
            self::CREDITOR_COUNTRY_TO,
            self::CREDITOR_COUNTRY_TP,
            self::CREDITOR_COUNTRY_TR,
            self::CREDITOR_COUNTRY_TT,
            self::CREDITOR_COUNTRY_TV,
            self::CREDITOR_COUNTRY_TW,
            self::CREDITOR_COUNTRY_TZ,
            self::CREDITOR_COUNTRY_UA,
            self::CREDITOR_COUNTRY_UG,
            self::CREDITOR_COUNTRY_UK,
            self::CREDITOR_COUNTRY_UM,
            self::CREDITOR_COUNTRY_US,
            self::CREDITOR_COUNTRY_UY,
            self::CREDITOR_COUNTRY_UZ,
            self::CREDITOR_COUNTRY_VA,
            self::CREDITOR_COUNTRY_VC,
            self::CREDITOR_COUNTRY_VE,
            self::CREDITOR_COUNTRY_VG,
            self::CREDITOR_COUNTRY_VI,
            self::CREDITOR_COUNTRY_VN,
            self::CREDITOR_COUNTRY_VU,
            self::CREDITOR_COUNTRY_WF,
            self::CREDITOR_COUNTRY_WS,
            self::CREDITOR_COUNTRY_XK,
            self::CREDITOR_COUNTRY_YE,
            self::CREDITOR_COUNTRY_YT,
            self::CREDITOR_COUNTRY_YU,
            self::CREDITOR_COUNTRY_ZA,
            self::CREDITOR_COUNTRY_ZM,
            self::CREDITOR_COUNTRY_ZR,
            self::CREDITOR_COUNTRY_ZW,
            self::CREDITOR_COUNTRY_UNKNOWN_DEFAULT_OPEN_API,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('creditorCountry', $data ?? [], null);
        $this->setIfExists('debtorIban', $data ?? [], null);
        $this->setIfExists('debtorName', $data ?? [], null);
        $this->setIfExists('reference', $data ?? [], null);
        $this->setIfExists('customer', $data ?? [], null);
        $this->setIfExists('customerHandle', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['creditorCountry'] === null) {
            $invalidProperties[] = "'creditorCountry' can't be null";
        }
        $allowedValues = $this->getCreditorCountryAllowableValues();
        if (!is_null($this->container['creditorCountry']) && !in_array($this->container['creditorCountry'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'creditorCountry', must be one of '%s'",
                $this->container['creditorCountry'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['debtorIban'] === null) {
            $invalidProperties[] = "'debtorIban' can't be null";
        }
        if ($this->container['debtorName'] === null) {
            $invalidProperties[] = "'debtorName' can't be null";
        }
        if ((mb_strlen($this->container['debtorName']) < 1)) {
            $invalidProperties[] = "invalid value for 'debtorName', the character length must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets creditorCountry
     *
     * @return string
     */
    public function getCreditorCountry()
    {
        return $this->container['creditorCountry'];
    }

    /**
     * Sets creditorCountry
     *
     * @param string $creditorCountry Mandatory country of creditor, in [ISO 3166-1 alpha-2](http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)
     *
     * @return self
     */
    public function setCreditorCountry($creditorCountry)
    {
        if (is_null($creditorCountry)) {
            throw new \InvalidArgumentException('non-nullable creditorCountry cannot be null');
        }
        $allowedValues = $this->getCreditorCountryAllowableValues();
        if (!in_array($creditorCountry, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'creditorCountry', must be one of '%s'",
                    $creditorCountry,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['creditorCountry'] = $creditorCountry;

        return $this;
    }

    /**
     * Gets debtorIban
     *
     * @return string
     */
    public function getDebtorIban()
    {
        return $this->container['debtorIban'];
    }

    /**
     * Sets debtorIban
     *
     * @param string $debtorIban Mandatory debtor IBAN
     *
     * @return self
     */
    public function setDebtorIban($debtorIban)
    {
        if (is_null($debtorIban)) {
            throw new \InvalidArgumentException('non-nullable debtorIban cannot be null');
        }
        $this->container['debtorIban'] = $debtorIban;

        return $this;
    }

    /**
     * Gets debtorName
     *
     * @return string
     */
    public function getDebtorName()
    {
        return $this->container['debtorName'];
    }

    /**
     * Sets debtorName
     *
     * @param string $debtorName Mandatory name of debtor (account holder name)
     *
     * @return self
     */
    public function setDebtorName($debtorName)
    {
        if (is_null($debtorName)) {
            throw new \InvalidArgumentException('non-nullable debtorName cannot be null');
        }

        if ((mb_strlen($debtorName) < 1)) {
            throw new \InvalidArgumentException('invalid length for $debtorName when calling ImportSepaPaymentMethodRequestDto., must be bigger than or equal to 1.');
        }

        $this->container['debtorName'] = $debtorName;

        return $this;
    }

    /**
     * Gets reference
     *
     * @return string|null
     */
    public function getReference()
    {
        return $this->container['reference'];
    }

    /**
     * Sets reference
     *
     * @param string|null $reference Optional reference given to the created payment method. Max length 64 with allowable characters [a-zA-Z0-9_.-@].
     *
     * @return self
     */
    public function setReference($reference)
    {
        if (is_null($reference)) {
            throw new \InvalidArgumentException('non-nullable reference cannot be null');
        }
        $this->container['reference'] = $reference;

        return $this;
    }

    /**
     * Gets customer
     *
     * @return \Frisbii\Model\CreateCustomer|null
     */
    public function getCustomer()
    {
        return $this->container['customer'];
    }

    /**
     * Sets customer
     *
     * @param \Frisbii\Model\CreateCustomer|null $customer customer
     *
     * @return self
     */
    public function setCustomer($customer)
    {
        if (is_null($customer)) {
            throw new \InvalidArgumentException('non-nullable customer cannot be null');
        }
        $this->container['customer'] = $customer;

        return $this;
    }

    /**
     * Gets customerHandle
     *
     * @return string|null
     */
    public function getCustomerHandle()
    {
        return $this->container['customerHandle'];
    }

    /**
     * Sets customerHandle
     *
     * @param string|null $customerHandle Customer reference to an existing customer. Either this argument or `customer` must be provided.
     *
     * @return self
     */
    public function setCustomerHandle($customerHandle)
    {
        if (is_null($customerHandle)) {
            throw new \InvalidArgumentException('non-nullable customerHandle cannot be null');
        }
        $this->container['customerHandle'] = $customerHandle;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


