<?php
/**
 * CheckoutAccountDataDtoTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Frisbii
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API
 *
 * REST API to manage Frisbii resources
 *
 * The version of the OpenAPI document: 1
 * Contact: support@frisbii.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Frisbii\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * CheckoutAccountDataDtoTest Class Doc Comment
 *
 * @category    Class
 * @description CheckoutAccountDataDto
 * @package     Frisbii
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CheckoutAccountDataDtoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CheckoutAccountDataDto"
     */
    public function testCheckoutAccountDataDto()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "account"
     */
    public function testPropertyAccount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "organisation"
     */
    public function testPropertyOrganisation()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "publicKey"
     */
    public function testPropertyPublicKey()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "agreements"
     */
    public function testPropertyAgreements()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
