<?php
/**
 * MeteredUsageRecordListResponseDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Frisbii
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API
 *
 * REST API to manage Frisbii resources
 *
 * OpenAPI spec version: 1
 * Contact: support@frisbii.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.52
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Frisbii;

use PHPUnit\Framework\TestCase;

/**
 * MeteredUsageRecordListResponseDtoTest Class Doc Comment
 *
 * @category    Class
 * @description MeteredUsageRecordListResponseDto
 * @package     Frisbii
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MeteredUsageRecordListResponseDtoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "MeteredUsageRecordListResponseDto"
     */
    public function testMeteredUsageRecordListResponseDto()
    {
    }

    /**
     * Test attribute "uuid"
     */
    public function testPropertyUuid()
    {
    }

    /**
     * Test attribute "product_name"
     */
    public function testPropertyProductName()
    {
    }

    /**
     * Test attribute "product_handle"
     */
    public function testPropertyProductHandle()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }

    /**
     * Test attribute "created"
     */
    public function testPropertyCreated()
    {
    }

    /**
     * Test attribute "units"
     */
    public function testPropertyUnits()
    {
    }

    /**
     * Test attribute "unit_label"
     */
    public function testPropertyUnitLabel()
    {
    }

    /**
     * Test attribute "billed"
     */
    public function testPropertyBilled()
    {
    }
}
