<?php
/**
 * SubscriptionEntitlementsDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Frisbii
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API
 *
 * REST API to manage Frisbii resources
 *
 * OpenAPI spec version: 1
 * Contact: support@frisbii.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.52
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Frisbii;

use PHPUnit\Framework\TestCase;

/**
 * SubscriptionEntitlementsDtoTest Class Doc Comment
 *
 * @category    Class
 * @description SubscriptionEntitlementsDto
 * @package     Frisbii
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SubscriptionEntitlementsDtoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "SubscriptionEntitlementsDto"
     */
    public function testSubscriptionEntitlementsDto()
    {
    }

    /**
     * Test attribute "entitlements"
     */
    public function testPropertyEntitlements()
    {
    }

    /**
     * Test attribute "additional_entitlements"
     */
    public function testPropertyAdditionalEntitlements()
    {
    }

    /**
     * Test attribute "excluded_entitlements"
     */
    public function testPropertyExcludedEntitlements()
    {
    }
}
