<?php
/**
 * UpdateMeteredBillingProductTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Frisbii
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API
 *
 * REST API to manage Frisbii resources
 *
 * OpenAPI spec version: 1
 * Contact: support@frisbii.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.52
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Frisbii;

use PHPUnit\Framework\TestCase;

/**
 * UpdateMeteredBillingProductTest Class Doc Comment
 *
 * @category    Class
 * @description UpdateMeteredBillingProduct
 * @package     Frisbii
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UpdateMeteredBillingProductTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "UpdateMeteredBillingProduct"
     */
    public function testUpdateMeteredBillingProduct()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "entitlements"
     */
    public function testPropertyEntitlements()
    {
    }

    /**
     * Test attribute "pricing"
     */
    public function testPropertyPricing()
    {
    }

    /**
     * Test attribute "all_plans"
     */
    public function testPropertyAllPlans()
    {
    }

    /**
     * Test attribute "usage_capture_method"
     */
    public function testPropertyUsageCaptureMethod()
    {
    }

    /**
     * Test attribute "auto_add_to_sub_on_usage"
     */
    public function testPropertyAutoAddToSubOnUsage()
    {
    }
}
