<?php
/**
 * AccountApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Frisbii
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API
 *
 * REST API to manage Frisbii resources
 *
 * The version of the OpenAPI document: 1
 * Contact: support@frisbii.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Frisbii\Test\Api;

use \Frisbii\Configuration;
use \Frisbii\ApiException;
use \Frisbii\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * AccountApiTest Class Doc Comment
 *
 * @category Class
 * @package  Frisbii
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AccountApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createPrivateKey
     *
     * Create private key.
     *
     */
    public function testCreatePrivateKey()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createPublicKey
     *
     * Create public key.
     *
     */
    public function testCreatePublicKey()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for expirePrivateKey
     *
     * Expire private key.
     *
     */
    public function testExpirePrivateKey()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for expirePublicKey
     *
     * Expire public key.
     *
     */
    public function testExpirePublicKey()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for generateWebhookSecret
     *
     * Generate new webhook secret.
     *
     */
    public function testGenerateWebhookSecret()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCurrentAccount
     *
     * Get account.
     *
     */
    public function testGetCurrentAccount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getDiscountSettings
     *
     * Get discount settings.
     *
     */
    public function testGetDiscountSettings()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getMailSettings
     *
     * Get mail settings.
     *
     */
    public function testGetMailSettings()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getMfaSettings
     *
     * Get account MFA settings.
     *
     */
    public function testGetMfaSettings()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPrivateKeysMasked
     *
     * Get list of masked private keys.
     *
     */
    public function testGetPrivateKeysMasked()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPublicKeys
     *
     * Get list of public keys.
     *
     */
    public function testGetPublicKeys()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getTerms
     *
     * Get terms.
     *
     */
    public function testGetTerms()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getWebhookSettings
     *
     * Get webhook settings.
     *
     */
    public function testGetWebhookSettings()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateAccountJson
     *
     * Update account.
     *
     */
    public function testUpdateAccountJson()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateDiscountSettings
     *
     * Update discount settings.
     *
     */
    public function testUpdateDiscountSettings()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateMailSettingsJson
     *
     * Update mail settings.
     *
     */
    public function testUpdateMailSettingsJson()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateMfaSettings
     *
     * Update account MFA settings.
     *
     */
    public function testUpdateMfaSettings()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateTerms
     *
     * Create or update terms.
     *
     */
    public function testUpdateTerms()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateWebhookSettingsJson
     *
     * Update webhook settings.
     *
     */
    public function testUpdateWebhookSettingsJson()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
