<?php
/**
 * AdditionalCostApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Frisbii
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API
 *
 * REST API to manage Frisbii resources
 *
 * The version of the OpenAPI document: 1
 * Contact: support@frisbii.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Frisbii\Test\Api;

use \Frisbii\Configuration;
use \Frisbii\ApiException;
use \Frisbii\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * AdditionalCostApiTest Class Doc Comment
 *
 * @category Class
 * @package  Frisbii
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AdditionalCostApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for cancelAdditionalCost
     *
     * Cancel pending additional cost.
     *
     */
    public function testCancelAdditionalCost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createAdditionalCostJson
     *
     * Create additional cost.
     *
     */
    public function testCreateAdditionalCostJson()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAdditionalCost
     *
     * Get additional cost.
     *
     */
    public function testGetAdditionalCost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAdditionalCosts
     *
     * Get additional costs for subscription.
     *
     */
    public function testGetAdditionalCosts()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
