<?php
/**
 * CustomerApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Frisbii
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API
 *
 * REST API to manage Frisbii resources
 *
 * OpenAPI spec version: 1
 * Contact: support@frisbii.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.52
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Frisbii;

use Frisbii\Configuration;
use Frisbii\ApiException;
use Frisbii\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CustomerApiTest Class Doc Comment
 *
 * @category Class
 * @package  Frisbii
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CustomerApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createCustomerInvoice
     *
     * Create invoice for customer.
     *
     */
    public function testCreateCustomerInvoice()
    {
    }

    /**
     * Test case for createCustomerJson
     *
     * Create customer.
     *
     */
    public function testCreateCustomerJson()
    {
    }

    /**
     * Test case for createCustomerNoteJson
     *
     * Create customer note.
     *
     */
    public function testCreateCustomerNoteJson()
    {
    }

    /**
     * Test case for deleteCustomer
     *
     * Delete customer.
     *
     */
    public function testDeleteCustomer()
    {
    }

    /**
     * Test case for deleteMetadata2
     *
     * Delete metadata.
     *
     */
    public function testDeleteMetadata2()
    {
    }

    /**
     * Test case for getCustomer
     *
     * Get customer.
     *
     */
    public function testGetCustomer()
    {
    }

    /**
     * Test case for getCustomerNotes
     *
     * Get customer notes.
     *
     */
    public function testGetCustomerNotes()
    {
    }

    /**
     * Test case for getMetadata2
     *
     * Get metadata.
     *
     */
    public function testGetMetadata2()
    {
    }

    /**
     * Test case for updateCustomerJson
     *
     * Update customer.
     *
     */
    public function testUpdateCustomerJson()
    {
    }

    /**
     * Test case for updateMetadata2
     *
     * Create or update metadata.
     *
     */
    public function testUpdateMetadata2()
    {
    }
}
